# Generated by Django 5.2.4 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
